name: Build Vue
on: 
 workflow_dispatch:
 push:

 issues:
   types:
     - closed
env:
  gitemail: temp@foo.mail
  gitname: temp
  username: alphaleadership
  useyarn: false
  cname: none
  gitmsg: update


permissions:
  actions: write
  attestations: write
  checks: write
  contents: write
  deployments: write
  id-token: write
  issues: write
  discussions: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write
concurrency:
  group: "build"
  cancel-in-progress: true
jobs:
  build_vue:
    
    
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v4
   
  
    
          
   
    - name: Build-Vue
      
      run: |
              git config --global user.email "${{ env.gitemail }}"
              git config --global user.name "${{ env.gitname }}"
              
              cd dist
              
              git init
              
              git remote add origin https://${{ env.username }}:${{ SECRETS.TOKEN }}@github.com/thomas-iniguez-visioli/blog-cine.git -m pages
              git fetch
              echo fetch
              git branch -m pages
              echo branch
              
              git add . 
              
              git commit -m temp
              
              git branch --set-upstream-to=origin 
              echo branch 2
              git remote -v
              echo test
              
              git fetch
              echo fetch
              git add . * */*
              git commit -m "temp"
              git merge --allow-unrelated-histories -v -m "merge" origin/pages
              git pull --ff-only
              git add .
              echo pull
             
              cd ..
               cd cdn
              
              git init
              
              git remote add origin https://${{ env.username }}:${{ SECRETS.TOKEN }}@github.com/thomas-iniguez-visioli/cdn.git -m main
              git fetch
              echo fetch
              git branch -m main
              echo branch
              echo temp >log.txt
              git add *  
              git commit -m temp
              
              git branch --set-upstream-to=origin 
              echo branch 2
              git remote -v
              echo test
              git fetch
              echo fetch
              git pull  --rebase
              git add . && git rebase --continue
              echo pull
             
              cd ..
              if [ true ==  ${{ env.useyarn }} ]; then yarn install --frozen-lockfile; else npm i; fi
              if [ true ==  ${{ env.useyarn }} ]; then yarn build; else npm run build; fi
           
              git pull 
              git push  
              cd dist
              ln -s index.html 404.html
              if [ "none" !=  ${{ env.cname }} ]; then echo '${{ env.cname }}' > CNAME; fi
              
              git add -A
              git commit -m '${{ env.gitmsg }}'
              if ! git diff --quiet remotes/origin/HEAD; then   git push ; fi
              cd ..
              cd cdn
              
              if [ "none" !=  ${{ env.cname }} ]; then echo '${{ env.cname }}' > CNAME; fi
              
              git add -A
              git commit -m '${{ env.gitmsg }}'
              if ! git diff --quiet remotes/origin/HEAD; then   git push ; fi
              cd ..
              git add -A
              git commit -m "update"
              git push 
        
    
   
