name: Build Vue
on: 
 workflow_dispatch:
 push:

 issues:
   types:
     - closed
env:
  gitemail: temp@foo.mail
  gitname: temp
  username: alphaleadership
  useyarn: false
  cname: none
  gitmsg: update


permissions:
  actions: write
  attestations: write
  checks: write
  contents: write
  deployments: write
  id-token: write
  issues: write
  discussions: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write
concurrency:
  group: "build"
  cancel-in-progress: true
jobs:
  build_vue:
    
    
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v4
   
  
    
          
   
    - name: Build-Vue
      
      run: |
              git config --global user.email "${{ env.gitemail }}"
              git config --global user.name "${{ env.gitname }}"
              git config pull.rebase true --global
              mkdir -p dist cdn
              cd cdn
              git init
              git remote add origin https://${{ env.username }}:${{ SECRETS.TOKEN }}@github.com/thomas-iniguez-visioli/cdn.git
              git fetch origin
              git checkout -t origin/main
              cd ..
              cd dist
              git init
              git remote add origin https://${{ env.username }}:${{ SECRETS.TOKEN }}@github.com/thomas-iniguez-visioli/blog-cine.git
              git fetch origin
              git reset --soft origin/pages
              git add * */*
              git checkout -t origin/pages
              
              echo "node_modules" > .gitignore
              git add .gitignore * */*
              git commit -m "7"
              cd ..
              if [ true ==  ${{ env.useyarn }} ]; then yarn install --frozen-lockfile; else npm i; fi
              if [ true ==  ${{ env.useyarn }} ]; then yarn build; else npm run build; fi
             
              cd dist
               git add -A
              git commit -m '${{ env.gitmsg }}'
              if ! git diff --quiet remotes/origin/pages; then   git push ; fi
